apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server
  replicas: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: neo73/api-server
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8989